on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    if: github.ref == 'refs/heads/main'
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '18.19.0'

    - name: Install Yarn
      run: npm install -g yarn

    - name: 🔨 Build Project
      run: |
        yarn
        yarn build

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: 23.108.108.219
        username: heber
        password: Admin007@
        port: 22
        source: dist/*
        target: /home/heber/apps/secretaria_calendario/
        overwrite: true
        strip_components: 1